services:
  db:
    container_name: gosci_postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - my_database:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: gosci_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_MODE: ${PGADMIN_CONFIG_MODE}
    ports:
      - 5050:80
    volumes:
      - my_pgadmin:/var/lib/pgadmin

volumes:
  my_database:
  my_pgadmin:
